name: "ve-mqtt"
description: "ve-mqtt addon"
version: "1.0.0"
slug: "ve-mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
full_access: true
#devices: 
#  /dev/ttyVICTRON
